---
name: "Install LLVM and Clang"
description: "Installs LLVM and Clang on CI runners"
inputs:
  version:
    description: "Which version of LLVM to install"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install LLVM and Clang
      if: ${{ runner.environment != 'self-hosted' && !contains(runner.os, 'macos') }}
      shell: bash
      run: |
        # if clang-version is already installed return
        if which clang-${{ inputs.version }} > /dev/null; then
          exit 0
        fi

        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ inputs.version }}
        rm llvm.sh
        sudo apt-get install -y clang-tidy-${{ inputs.version }} clang-format-${{ inputs.version }}

    - name: Install LLVM and Clang on macOS
      if: contains(matrix.os, 'macos')
      shell: bash
      run: |
        brew install llvm@${{ inputs.version }}
        echo "PATH=/opt/homebrew/opt/llvm@${{ inputs.version }}/bin:$PATH" >> $GITHUB_ENV
        echo "LDFLAGS=-L/opt/homebrew/opt/llvm@${{ inputs.version }}/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/opt/homebrew/opt/llvm@${{ inputs.version }}/include" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=/opt/homebrew/opt/llvm@${{ inputs.version }}" >> $GITHUB_ENV
